default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 17e12779811926f000bdfa1795f9e3735dd71ac3 # frozen: 0.26
    hooks:
      - id: validate-pyproject
        additional_dependencies:
          - validate-pyproject-schema-store[all]==2026.09.04

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 321478e58f4938179c6b86e4ddfa923d1547a49b # frozen: v0.16.6
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes", "--unsafe-fixes"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        args: ["--ignore-words-list=lief,LIEF", "-w", "--skip=*.rtf"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 34b241d706d24e4ccb69e38f9f0fa190b5f486ec # frozen: v23.1.0
    hooks:
      - id: clang-format
        exclude: |
          (?x)^(src/freeze_core/include/pythoncapi_compat.h)$
        types_or: [c, c++]

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # frozen: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0ee178619d696787ca73d210cc191d720868c631 # frozen: v3.9.6
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: 743d21e292f7a36ed70cc2318aa3c8711b1e0437 # frozen: v0.0.78
    hooks:
      - id: ty
        args: [--no-sync]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: cef8b8350da46d8114c7e6b7272aebdccdf193ce # frozen: v1.30.0
    hooks:
      - id: zizmor
        args: ["--fix=all", "--no-progress", "-p"]

  - repo: local
    hooks:
      - id: pythoncapi
        name: upgrade pythoncapi
        entry: ci/pythoncapi.sh
        language: system
        files: ^(src/freeze_core/include/pythoncapi_compat.h|src/freeze_core/.*.c)$

      - id: requirements
        name: requirements
        language: system
        entry: python ci/requirements.py
        files: ^(pyproject.toml|requirements.txt|requirements-dev.txt|
          tests/requirements.txt
          )$

      - id: lint-shell
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
